module main

import os
import grammar
import parser
import time
import strings

fn main() {
	args := os.args

	if args.len < 2 {
		println('Usage: vpegu <grammar_file.peg> [--output <output_file.v>] [--test <input_string>]')
		exit(1)
	}

	grammar_file := args[1]

	if !os.exists(grammar_file) {
		eprintln("Error: Grammar file '${grammar_file}' not found")
		exit(1)
	}

	grammar_content := os.read_file(grammar_file) or {
		eprintln('Error: Cannot read grammar file: ${err}')
		exit(1)
	}

	mut grammar_parser := parser.new_parser()
	parsed_grammar := grammar_parser.parse(grammar_content) or {
		eprintln('Error: Failed to parse grammar: ${err}')
		exit(1)
	}

	mut output_file := ''
	mut test_input := ''

	if args.len > 2 {
		mut i := 2
		for i < args.len {
			match args[i] {
				'--output' {
					if i + 1 >= args.len {
						eprintln('Error: --output requires a filename')
						exit(1)
					}
					output_file = args[i + 1]
					i += 2
				}
				'--test' {
					if i + 1 >= args.len {
						eprintln('Error: --test requires input string')
						exit(1)
					}
					test_input = args[i + 1]
					i += 2
				}
				else {
					eprintln("Error: Unknown option '${args[i]}'")
					exit(1)
				}
			}
		}
	}

	if test_input != '' {
		test_parser_internal(parsed_grammar, test_input)
	}

	if output_file != '' {
		generate_parser_file(parsed_grammar, output_file)
	} else if test_input == '' {
		println(generate_parser_code(parsed_grammar))
	}
}

fn test_parser_internal(g grammar.Tree, input string) {
	mut p := parser.new_packrat_parser(g)
	result := p.parse(input) or {
		println('Parse failed: ${err}')
		return
	}
	println('Parse successful!')
	println('Result: ${result}')
}

fn generate_parser_file(g grammar.Tree, output_file string) {
	code := generate_parser_code(g)
	os.write_file(output_file, code) or {
		eprintln('Error: Cannot write to ${output_file}: ${err}')
		exit(1)
	}
	println('Parser generated successfully: ${output_file}')
}

fn generate_parser_code(g grammar.Tree) string {
	mut sb := strings.new_builder(10000)

	sb.writeln('// Generated by VPEG Parser Generator (vpegu)')
	sb.writeln('// Generated at: ${time.now().str()}')
	sb.writeln('')
	sb.writeln('module main')
	sb.writeln('')
	sb.writeln('import os')
	sb.writeln('')
	sb.writeln('pub struct PackratParser {')
	sb.writeln('pub mut:')
	sb.writeln('    input string')
	sb.writeln('    memo_cache []ParseResult')
	sb.writeln('    num_rules int')
	sb.writeln('}')
	sb.writeln('')
	sb.writeln('pub struct ParseResult {')
	sb.writeln('pub:')
	sb.writeln('    success      bool')
	sb.writeln('    value        string')
	sb.writeln('    end_position int')
	sb.writeln('}')
	sb.writeln('')

	// Generate rule methods
	for i, rule in g.rules {
		sb.writeln(generate_rule_method(rule, i))
	}

	sb.writeln('pub fn (mut p PackratParser) parse() ParseResult {')
	sb.writeln('    p.num_rules = ${g.rules.len}')
	sb.writeln('    p.memo_cache = []ParseResult{len: (p.input.len + 1) * p.num_rules, init: ParseResult{success: false, end_position: -1}}')
	if g.rules.len > 0 {
		rule_name_lower := g.rules[0].name.to_lower()
		sb.writeln('    return p.parse_${rule_name_lower}(0)')
	} else {
		sb.writeln("    return ParseResult{false, '', 0}")
	}
	sb.writeln('}')
	sb.writeln('')

	sb.writeln(generate_helper_methods())
	sb.writeln(generate_main_function())

	return sb.str()
}

fn generate_rule_method(rule grammar.Rule, id int) string {
	mut sb := strings.new_builder(1000)
	rule_name_lower := rule.name.to_lower()
	sb.writeln('// Rule: ${rule.name}')
	sb.writeln('fn (mut p PackratParser) parse_${rule_name_lower}(pos int) ParseResult {')
	sb.writeln('    idx := ${id} * (p.input.len + 1) + pos')
	sb.writeln('    if p.memo_cache[idx].end_position != -1 {')
	sb.writeln('        return p.memo_cache[idx]')
	sb.writeln('    }')
	sb.writeln('')

	expr_code := generate_expression_code(rule.expr, 'pos', 0)
	sb.writeln('    result := ${expr_code}')
	sb.writeln('')
	sb.writeln('    p.memo_cache[idx] = result')
	sb.writeln('    return result')
	sb.writeln('}')
	return sb.str()
}

fn generate_expression_code(expr grammar.Expression, pos_var string, depth int) string {
	match expr.kind {
		.sequence {
			return generate_sequence_code(expr, pos_var, depth)
		}
		.alternate {
			return generate_choice_code(expr, pos_var, depth)
		}
		.star, .plus, .query {
			return generate_repetition_code(expr, pos_var, depth)
		}
		.peek_for, .peek_not {
			return generate_predicate_code(expr, pos_var, depth)
		}
		.name {
			rule_name_lower := expr.value.to_lower()
			return 'p.parse_${rule_name_lower}(${pos_var})'
		}
		.literal {
			escaped := expr.value.replace("'", "\\'")
			return "p.match_literal(${pos_var}, '${escaped}')"
		}
		.character_class {
			return generate_character_class_code(expr, pos_var)
		}
		.dot {
			return 'p.match_dot(${pos_var})'
		}
		.action {
			if expr.items.len > 0 {
				return generate_expression_code(expr.items[0], pos_var, depth)
			}
			return "ParseResult{true, '', ${pos_var}}"
		}
		else {
			return "ParseResult{false, '', ${pos_var}}"
		}
	}
}

fn generate_sequence_code(expr grammar.Expression, pos_var string, depth int) string {
	mut sb := strings.new_builder(500)
	sb.write_string('fn(mut p PackratParser, pos int) ParseResult {')
	sb.write_string(' mut cur_pos := pos;')
	sb.write_string(' mut vals := []string{};')
	for i, sub_expr in expr.items {
		sb.write_string(' res_${i} := ${generate_expression_code(sub_expr, 'cur_pos',
			depth + 1)};')
		sb.write_string(" if !res_${i}.success { return ParseResult{false, '', pos} };")
		sb.write_string(' cur_pos = res_${i}.end_position;')
		sb.write_string(' vals << res_${i}.value;')
	}
	sb.write_string(" return ParseResult{true, vals.join(''), cur_pos}")
	sb.write_string(' }(mut p, ${pos_var})')
	return sb.str()
}

fn generate_choice_code(expr grammar.Expression, pos_var string, depth int) string {
	mut sb := strings.new_builder(500)
	sb.write_string('fn(mut p PackratParser, pos int) ParseResult {')
	for i, sub_expr in expr.items {
		sb.write_string(' res_${i} := ${generate_expression_code(sub_expr, 'pos', depth + 1)};')
		sb.write_string(' if res_${i}.success { return res_${i} };')
	}
	sb.write_string(" return ParseResult{false, '', pos}")
	sb.write_string(' }(mut p, ${pos_var})')
	return sb.str()
}

fn generate_repetition_code(expr grammar.Expression, pos_var string, depth int) string {
	mut sb := strings.new_builder(500)
	min := if expr.kind == .plus { 1 } else { 0 }
	max := if expr.kind == .query { 1 } else { -1 }

	sb.write_string('fn(mut p PackratParser, pos int) ParseResult {')
	sb.write_string(' mut cur_pos := pos;')
	sb.write_string(' mut vals := []string{};')
	sb.write_string(' mut count := 0;')
	sb.write_string(' for {')
	if max != -1 {
		sb.write_string(' if count >= ${max} { break };')
	}
	if expr.items.len > 0 {
		sb.write_string(' res := ${generate_expression_code(expr.items[0], 'cur_pos',
			depth + 1)};')
		sb.write_string(' if !res.success { break };')
		sb.write_string(' vals << res.value;')
		sb.write_string(' cur_pos = res.end_position;')
		sb.write_string(' count++;')
		sb.write_string(' if cur_pos == pos { break };')
	} else {
		sb.write_string(' break;')
	}
	sb.write_string(' };')
	sb.write_string(" if count < ${min} { return ParseResult{false, '', pos} };")
	sb.write_string(" return ParseResult{true, vals.join(''), cur_pos}")
	sb.write_string(' }(mut p, ${pos_var})')
	return sb.str()
}

fn generate_predicate_code(expr grammar.Expression, pos_var string, depth int) string {
	is_and := expr.kind == .peek_for
	inner := if expr.items.len > 0 {
		generate_expression_code(expr.items[0], pos_var, depth + 1)
	} else {
		"ParseResult{false, '', ${pos_var}}"
	}

	mut sb := strings.new_builder(200)
	sb.write_string('fn(mut p PackratParser, pos int) ParseResult {')
	sb.write_string(' res := ${inner};')
	if is_and {
		sb.write_string(" if res.success { return ParseResult{true, '', pos} };")
	} else {
		sb.write_string(" if !res.success { return ParseResult{true, '', pos} };")
	}
	sb.write_string(" return ParseResult{false, '', pos}")
	sb.write_string(' }(mut p, ${pos_var})')
	return sb.str()
}

fn generate_character_class_code(expr grammar.Expression, pos_var string) string {
	pattern := expr.value
	mut sb := strings.new_builder(200)
	sb.write_string('fn(mut p PackratParser, pos int) ParseResult {')
	sb.write_string(" if pos >= p.input.len { return ParseResult{false, '', pos} };")
	sb.write_string(' char := p.input[pos];')

	if pattern.len == 3 && pattern[1] == `-` {
		start := pattern[0]
		end := pattern[2]
		sb.write_string(' if char >= `${start}` && char <= `${end}` {')
		sb.write_string(' return ParseResult{true, char.str(), pos + 1}')
		sb.write_string(' };')
	} else {
		sb.write_string(" if '${pattern}'.contains(char.str()) {")
		sb.write_string(' return ParseResult{true, char.str(), pos + 1}')
		sb.write_string(' };')
	}
	sb.write_string(" return ParseResult{false, '', pos}")
	sb.write_string(' }(mut p, ${pos_var})')
	return sb.str()
}

fn generate_helper_methods() string {
	return "
fn (mut p PackratParser) match_literal(pos int, literal string) ParseResult {
    if pos + literal.len > p.input.len {
        return ParseResult{false, '', pos}
    }
    if p.input[pos..pos + literal.len] == literal {
        return ParseResult{true, literal, pos + literal.len}
    }
    return ParseResult{false, '', pos}
}

fn (mut p PackratParser) match_dot(pos int) ParseResult {
    if pos >= p.input.len {
        return ParseResult{false, '', pos}
    }
    return ParseResult{true, p.input[pos..pos+1], pos + 1}
}
"
}

fn generate_main_function() string {
	return "
fn main() {
    args := os.args
    if args.len < 2 {
        println('Usage: parser <input_string>')
        return
    }
    input := args[1]
    mut p := PackratParser{
        input: input
    }
    result := p.parse()
    if result.success {
        println('Parse successful!')
        println('Result: ' + result.value)
    } else {
        println('Parse failed at position ' + result.end_position.str())
    }
}
"
}
