module main

import os
import grammar
import parser

fn main() {
	args := os.args
	
	if args.len < 2 {
		println("Usage: vpegu <grammar_file.peg>")
		println("       vpegu <grammar_file.peg> --output <output_file.v>")
		println("       vpegu <grammar_file.peg> --test <test_input>")
		exit(1)
	}
	
	grammar_file := args[1]
	
	// Check if file exists
	if !os.exists(grammar_file) {
		eprintln("Error: Grammar file '${grammar_file}' not found")
		exit(1)
	}
	
	// Read grammar file
	grammar_content := os.read_file(grammar_file) or {
		eprintln("Error: Cannot read grammar file: ${err}")
		exit(1)
	}
	
	// Parse grammar
	mut grammar_parser := grammar.new_grammar_parser()
	parsed_grammar := grammar_parser.parse(grammar_content) or {
		eprintln("Error: Failed to parse grammar: ${err}")
		exit(1)
	}
	
	// Handle command line options
	if args.len > 2 {
		match args[2] {
			"--output" {
				if args.len < 4 {
					eprintln("Error: --output requires a filename")
					exit(1)
				}
				generate_parser_file(parsed_grammar, args[3])
			}
			"--test" {
				if args.len < 4 {
					eprintln("Error: --test requires input string")
					exit(1)
				}
				test_parser(parsed_grammar, args[3])
			}
			else {
				eprintln("Error: Unknown option '${args[2]}'")
				exit(1)
			}
		}
	} else {
		// Default: generate parser to stdout
		generate_parser_code(parsed_grammar)
	}
}

// generate_parser_file creates a V file with the generated parser
fn generate_parser_file(grammar grammar.Grammar, output_file string) {
	code := generate_parser_code(grammar)
	
	os.write_file(output_file, code) or {
		eprintln("Error: Cannot write to ${output_file}: ${err}")
		exit(1)
	}
	
	println("Parser generated successfully: ${output_file}")
	println("You can compile it with: v ${output_file}")
}

// generate_parser_code generates the parser code as a string
fn generate_parser_code(g grammar.Grammar) string {
	mut code := []string{}
	
	// Header
	code << "// Generated by V PEG Parser Generator (vpegu)"
	code << "// Grammar: ${g.name}"
	code << "// Generated at: ${get_current_timestamp()}"
	code << ""
	
	// Module declaration
	code << "module main"
	code << ""
	
	// Imports
	code << "import os"
	code << ""
	
	// Generate the parser struct and methods
	code << "// Packrat Parser Implementation"
	code << "pub struct PackratParser {"
	code << "mut:"
	code << "    input string"
	code << "    position int"
	code << "    memo_cache map[string]ParseResult"
	code << "}"
	
	code << ""
	code << "pub struct ParseResult {"
	code << "pub:"
	code << "    success bool"
	code << "    value string"
	code << "    end_position int"
	code << "}"
	code << ""
	
	// Generate rule methods
	for rule in g.rules {
		code << generate_rule_method(rule, g)
		code << ""
	}
	
	// Generate main parse entry point
	code << "// Main parse function"
	code << "pub fn (mut p PackratParser) parse() ParseResult {"
	code << "    return p.parse_${g.rules[0].name}(0)"
	code << "}"
	code << ""
	
	// Generate helper methods
	code << generate_helper_methods()
	
	// Generate main function for testing
	code << generate_main_function()
	
	return code.join("\n")
}

// generate_rule_method generates code for a specific rule
fn generate_rule_method(rule grammar.Rule, g grammar.Grammar) string {
	mut code := []string{}
	
	code << "// Rule: ${rule.name}"
	code << "fn (mut p PackratParser) parse_${rule.name}(pos int) ParseResult {"
	code << "    cache_key := \"${rule.name}_\" + pos.str()"
	code << "    if cache_key in p.memo_cache {"
	code << "        return p.memo_cache[cache_key]"
	code << "    }"
	code << ""
	
	// Generate expression parsing
	expr_code := generate_expression_code(rule.expression, "pos", 0)
	code << "    result := ${expr_code}"
	code << ""
	
	code << "    p.memo_cache[cache_key] = result"
	code << "    return result"
	code << "}"
	
	return code.join("\n")
}

// generate_expression_code generates code for parsing an expression
fn generate_expression_code(expr grammar.Expression, pos_var string, depth int) string {
	match expr.type_of() {
		.sequence {
			return generate_sequence_code(expr, pos_var, depth)
		}
		.choice {
			return generate_choice_code(expr, pos_var, depth)
		}
		.zero_or_more, .one_or_more, .optional {
			return generate_repetition_code(expr, pos_var, depth)
		}
		.and_predicate, .not_predicate {
			return generate_predicate_code(expr, pos_var, depth)
		}
		.rule_reference {
			return "p.parse_${expr.rule_name}(${pos_var})"
		}
		.literal {
			escaped := expr.literal_value.replace("'", "\\'")
			return "p.match_literal(${pos_var}, '${escaped}')"
		}
		.character_class {
			return generate_character_class_code(expr, pos_var)
		}
		.group {
			return generate_expression_code(expr.expression, pos_var, depth)
		}
		.semantic_action {
			return generate_semantic_action_code(expr, pos_var, depth)
		}
	}
	
	return "ParseResult{false, \"\", ${pos_var}}"
}

// generate_sequence_code generates code for sequence parsing
fn generate_sequence_code(expr grammar.Expression, pos_var string, depth int) string {
	mut code := []string{}
	mut var_name := "pos_${depth}"
	
	code << "{"
	code << "    mut ${var_name} := ${pos_var}"
	
	for i, sub_expr in expr.sequence_expressions {
		sub_var := "res_${depth}_${i}"
		code << "    ${sub_var} := ${generate_expression_code(sub_expr, var_name, depth + 1)}"
		code << "    if !${sub_var}.success {"
		code << "        return ParseResult{false, \"\", ${pos_var}}"
		code << "    }"
		code << "    ${var_name} = ${sub_var}.end_position"
	}
	
	code << "    return ParseResult{true, \"\", ${var_name}}"
	code << "}"
	
	return code.join("\n")
}

// generate_choice_code generates code for choice parsing
fn generate_choice_code(expr grammar.Expression, pos_var string, depth int) string {
	mut code := []string{}
	
	code << "{"
	
	for i, sub_expr in expr.choice_expressions {
		result_var := "res_${depth}_${i}"
		if i == 0 {
			code << "    ${result_var} := ${generate_expression_code(sub_expr, pos_var, depth + 1)}"
			code << "    if ${result_var}.success {"
			code << "        return ${result_var}"
			code << "    }"
		} else {
			code << "    ${result_var} := ${generate_expression_code(sub_expr, pos_var, depth + 1)}"
			code << "    if ${result_var}.success {"
			code << "        return ${result_var}"
			code << "    }"
		}
	}
	
	code << "    return ParseResult{false, \"\", ${pos_var}}"
	code << "}"
	
	return code.join("\n")
}

// generate_repetition_code generates code for repetition parsing
fn generate_repetition_code(expr grammar.Expression, pos_var string, depth int) string {
	mut code := []string{}
	mut var_name := "pos_${depth}"
	mut values_var := "values_${depth}"
	
	code << "{"
	code << "    mut ${var_name} := ${pos_var}"
	code << "    mut ${values_var} := []string{}"
	
	min_count := match expr.type_of() {
		.zero_or_more { 0 }
		.one_or_more { 1 }
		.optional { 0 }
		else { 0 }
	}
	
	max_count := match expr.type_of() {
		.optional { 1 }
		else { -1 }
	}
	
	code << "    count := 0"
	code << "    for {"
	
	if max_count != -1 {
		code << "        if count >= ${max_count} { break }"
	}
	
	sub_result := "res_${depth}"
	code << "        ${sub_result} := ${generate_expression_code(expr.repetition_expression, var_name, depth + 1)}"
	code << "        if !${sub_result}.success { break }"
	code << "        ${values_var} << ${sub_result}.value"
	code << "        ${var_name} = ${sub_result}.end_position"
	code << "        count++"
	code << "        if count > 1000 { break } // Safety limit"
	
	code << "    }"
	code << ""
	code << "    if count < ${min_count} {"
	code << "        return ParseResult{false, \"\", ${pos_var}}"
	code << "    }"
	code << ""
	
	// Handle result value
	match expr.type_of() {
		.optional {
			code << "    if ${values_var}.len == 0 {"
			code << "        return ParseResult{true, \"\", ${pos_var}}"
			code << "    } else {"
			code << "        return ParseResult{true, ${values_var}[0], ${var_name}}"
			code << "    }"
		}
		else {
			code << "    return ParseResult{true, ${values_var}.join(\"\"), ${var_name}}"
		}
	}
	
	code << "}"
	
	return code.join("\n")
}

// generate_predicate_code generates code for predicates
fn generate_predicate_code(expr grammar.Expression, pos_var string, depth int) string {
	is_and := expr.type_of() == .and_predicate
	
	sub_result := "res_${depth}"
	sub_code := generate_expression_code(expr.predicate_expression, pos_var, depth + 1)
	
	mut code := []string{}
	code << "{"
	code << "    ${sub_result} := ${sub_code}"
	
	if is_and {
		code << "    if ${sub_result}.success {"
		code << "        return ParseResult{true, \"\", ${pos_var}}"
		code << "    }"
	} else {
		code << "    if !${sub_result}.success {"
		code << "        return ParseResult{true, \"\", ${pos_var}}"
		code << "    }"
	}
	
	code << "    return ParseResult{false, \"\", ${pos_var}}"
	code << "}"
	
	return code.join("\n")
}

// generate_character_class_code generates code for character classes
fn generate_character_class_code(expr grammar.Expression, pos_var string) string {
	mut conditions := []string{}
	
	for range_expr in expr.character_ranges {
		start := range_expr.start
		end := range_expr.end
		
		if start == end {
			conditions << "p.input[${pos_var}] == '${start}'"
		} else {
			conditions << "(p.input[${pos_var}] >= '${start}' && p.input[${pos_var}] <= '${end}')"
		}
	}
	
	condition := conditions.join(" || ")
	
	mut code := []string{}
	code << "{"
	code << "    if ${pos_var} >= p.input.len {"
	code << "        return ParseResult{false, \"\", ${pos_var}}"
	code << "    }"
	code << "    if ${condition} {"
	code << "        return ParseResult{true, p.input[${pos_var}..${pos_var}+1], ${pos_var} + 1}"
	code << "    }"
	code << "    return ParseResult{false, \"\", ${pos_var}}"
	code << "}"
	
	return code.join("\n")
}

// generate_semantic_action_code generates code for semantic actions
fn generate_semantic_action_code(expr grammar.Expression, pos_var string, depth int) string {
	// For now, just parse the inner expression
	// In a full implementation, this would execute the action code
	return generate_expression_code(expr.action_expression, pos_var, depth)
}

// generate_helper_methods generates utility methods
fn generate_helper_methods() string {
	return "
// match_literal matches a literal string
fn (mut p PackratParser) match_literal(pos int, literal string) ParseResult {
    if pos + literal.len > p.input.len {
        return ParseResult{false, \"\", pos}
    }
    if p.input[pos..pos + literal.len] == literal {
        return ParseResult{true, literal, pos + literal.len}
    }
    return ParseResult{false, \"\", pos}
}
"
}

// generate_main_function generates a test main function
fn generate_main_function() string {
	return "
fn main() {
    if os.args.len < 2 {
        println(\"Usage: parser <input>\")
        return
    }
    
    input := os.args[1]
    mut parser := PackratParser{
        input: input
        position: 0
        memo_cache: map[string]ParseResult{}
    }
    
    result := parser.parse()
    
    if result.success {
        println(\"Parse successful!\")
        println(\"Result: \" + result.value)
        println(\"End position: \" + result.end_position.str())
    } else {
        println(\"Parse failed at position: \" + result.end_position.str())
    }
}
"
}

// get_current_timestamp returns current timestamp as string
fn get_current_timestamp() string {
	// Simple timestamp for now
	return "2025-12-23"
}
